name: "💄 Lint py code"

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:

  run:
    name: Lint py code
    runs-on: ubuntu-latest

    steps:

      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.0.0

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ~/.env
          installer-parallel: true

      - name: Install dependencies
        run: poetry install

      - name: Check black lint
        run: poetry run black --check --diff .

      - name: Check isort lint
        run: poetry run isort --check .

      - name: Check mypy lint
        run: poetry run mypy --ignore-missing-imports --check .
